version: '3'
services:
  db:
    container_name: aus-ddr-events-db
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    environment:
      POSTGRES_DB: ${AUS_DDR_EVENTS_DB_DB}
      POSTGRES_USER: ${AUS_DDR_EVENTS_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUS_DDR_EVENTS_DB_PASSWORD}
    ports:
      - 1235:5432
  dbPgAdmin:
    container_name: aus-ddr-events-db-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${AUS_DDR_EVENTS_PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${AUS_DDR_EVENTS_PGADMIN_PASSWORD}
    ports:
      - 1236:80