version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
  jira: circleci/jira@1.3.0
jobs:
  build:
    working_directory: ~/aus-ddr-api
    machine:
      image: ubuntu-2004:202101-01
    environment:
      - HEROKU_APP_NAME: aus-ddr-api
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Build application Docker image
          command: |
            docker build -t ${HEROKU_APP_NAME} .
      - heroku/push-docker-image:
          process-types: web
      - heroku/release-docker-image:
          process-types: web
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - production
          post-steps:
            - jira/notify
          filters:
            branches:
              only: master