version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:20.10.3-git
    environment:
      - HEROKU_APP_NAME: aus-ddr-api
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Build application Docker image
          command: |
            docker build -t ${HEROKU_APP_NAME} .
      - push-docker-image
      - release-docker-image
workflows:
  build_and_deploy:
    jobs:
      - build:
          context:
            - production
          post-steps:
            - jira/notify
          filters:
            branches:
              only: master