version: 2.1
orbs:
  jira: circleci/jira@1.3.0
jobs:
  install:
    working_directory: ~/aus-ddr-api
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    resource_class: medium
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: dotnet user-secrets set "Database:ConnectionString" "$DATABASE_CONNECTION_STRING"
      - run: dotnet restore
      - run: dotnet build
        
workflows:
  deploy:
    jobs:
      - install:
          context:
            - production
          post-steps:
            - jira/notify